language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

sudo: required

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/mantaray_utilities
    python: 3.6
